// nodeapp/web/src/app/journal-entries/page.tsx
"use client";

import { useEffect, useState } from "react";
import { apiGet } from "@/lib/api";

type Entry = {
  id: number;
  entry_date: string;
  description: string;
  debit_account: string;
  credit_account: string;
  amount: number;
};

function formatMoney(value: number) {
  const num = Number(value || 0);
  const prefix = num < 0 ? "-Rs " : "Rs ";
  return `${prefix}${Math.abs(num).toLocaleString("en-IN")}`;
}

export default function Page() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [entries, setEntries] = useState<Entry[]>([]);
  const [page, setPage] = useState(1);
  const [pages, setPages] = useState(1);

  async function load(targetPage: number) {
    setLoading(true);
    setError("");
    try {
      const payload = await apiGet(`/transactions?page=${targetPage}`);
      setEntries(payload?.entries || []);
      setPages(payload?.pagination?.pages || 1);
      setPage(payload?.pagination?.page || targetPage);
    } catch (err: any) {
      setError(err?.message || "Failed to load journal entries.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load(1);
  }, []);

  return (
    <div className="space-y-6">
      <div>
        <div className="h1">Journal Entries</div>
        <div className="subtle">Combined debit/credit view of journal entries.</div>
      </div>

      {error ? <div className="danger">{error}</div> : null}

      <div className="card">
        <div className="toolbar">
          <button
            className="button"
            type="button"
            onClick={() => load(Math.max(1, page - 1))}
            disabled={page <= 1}
          >
            Prev
          </button>
          <span className="meta">
            Page {page} of {pages}
          </span>
          <button
            className="button"
            type="button"
            onClick={() => load(Math.min(pages, page + 1))}
            disabled={page >= pages}
          >
            Next
          </button>
        </div>
      </div>

      {loading ? (
        <div className="meta">Loading...</div>
      ) : (
        <div className="card">
          <table className="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Debit</th>
                <th className="num">Amount</th>
                <th>Description</th>
                <th>Credit</th>
              </tr>
            </thead>
            <tbody>
              {entries.length === 0 ? (
                <tr>
                  <td colSpan={5} className="meta">
                    No journal entries found.
                  </td>
                </tr>
              ) : null}
              {entries.map((row) => (
                <tr key={row.id}>
                  <td>{row.entry_date}</td>
                  <td>{row.debit_account}</td>
                  <td className="num">{formatMoney(row.amount)}</td>
                  <td>{row.description}</td>
                  <td>{row.credit_account}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// frontend/src/routes/journal-entries/+page.svelte
<script>
  import { onMount } from "svelte";
  import { apiGet } from "$lib/api";
  import { toPeriodParam } from "$lib/period";
  import Table from "$lib/components/Table.svelte";
  import { page } from "$app/stores";
  import { formatInr } from "$lib/format";

  let data = null;
  let accountId = "";
  let period = "all";
  let startDate = "";
  let endDate = "";
  let error = "";
  let ready = false;

  const columns = [
    { header: "Date", render: (row) => row.entry_date },
    { header: "Debit Account", render: (row) => row.debit_account },
    { header: "Amount", render: (row) => formatInr(row.amount), align: "right" },
    { header: "Description", render: (row) => row.description },
    { header: "Credit Account", render: (row) => row.credit_account }
  ];

  function setPeriodForMode(mode, endParam, monthParam) {
    if (mode === "upto" && endParam) {
      period = "custom";
      startDate = "1900-01-01";
      endDate = endParam;
      return;
    }
    if (mode === "month" && monthParam) {
      const [y, m] = monthParam.split("-");
      const start = new Date(Number(y), Number(m) - 1, 1);
      const end = new Date(Number(y), Number(m), 0);
      period = "custom";
      startDate = start.toISOString().slice(0, 10);
      endDate = end.toISOString().slice(0, 10);
      return;
    }
    period = "all";
    startDate = "";
    endDate = "";
  }

  async function load(pageNum = 1) {
    try {
      error = "";
      const params = new URLSearchParams();
      params.set("period", toPeriodParam(period, startDate, endDate));
      if (accountId) params.set("account_id", accountId);
      params.set("page", String(pageNum));
      data = await apiGet(`/transactions?${params.toString()}`);
    } catch (err) {
      error = err.message || "Failed to load.";
    }
  }

  onMount(async () => {
    ready = true;
    const qs = $page.url.searchParams;
    const qsAccount = qs.get("account_id");
    const qsMode = qs.get("mode");
    const qsEnd = qs.get("end");
    const qsMonth = qs.get("month");

    if (qsAccount) {
      accountId = qsAccount;
    }
    setPeriodForMode(qsMode, qsEnd, qsMonth);

    await load(1);
  });

  $: if (ready) {
    accountId;
    period;
    startDate;
    endDate;
    load(1);
  }
</script>

<h1 class="page-title">Journal Entries</h1>
<p class="page-subtitle">Account-level drilldown.</p>

{#if error}
  <p class="danger">{error}</p>
{/if}

<div class="toolbar">
  <label>
    Account:&nbsp;
    <select bind:value={accountId}>
      {#if data?.accounts_for_select}
        {#each data.accounts_for_select as acc}
          <option value={acc.id}>{acc.path || acc.name}</option>
        {/each}
      {/if}
    </select>
  </label>
  <span class="meta">Total: {data?.pagination?.total ?? 0} entries</span>
</div>

<Table columns={columns} rows={data ? data.entries : []} />

<div class="toolbar">
  <button
    class="button"
    disabled={!data?.pagination?.has_prev}
    on:click={() => load((data?.pagination?.page || 1) - 1)}
  >
    Prev Page
  </button>
  <span class="meta">Page {data?.pagination?.page ?? 1} / {data?.pagination?.pages ?? 1}</span>
  <button
    class="button"
    disabled={!data?.pagination?.has_next}
    on:click={() => load((data?.pagination?.page || 1) + 1)}
  >
    Next Page
  </button>
</div>
