// nodeapp/web/src/app/ledger/page.tsx
"use client";

import { useEffect, useState } from "react";
import { apiGet } from "@/lib/api";

type Account = { id: number; name: string; path?: string };
type Entry = { id: number; entry_date: string; description: string; reference: string; notes: string };

const PERIODS = [
  { value: "ytd", label: "Year to Date" },
  { value: "current_month", label: "Current Month" },
  { value: "all", label: "All Time" }
];

export default function Page() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [accountId, setAccountId] = useState<number | null>(null);
  const [period, setPeriod] = useState("ytd");
  const [entries, setEntries] = useState<Entry[]>([]);

  async function loadAccounts() {
    setLoading(true);
    setError("");
    try {
      const payload = await apiGet("/transactions/accounts");
      setAccounts(payload?.accounts || []);
      if (payload?.accounts?.length) {
        setAccountId(payload.accounts[0].id);
      }
    } catch (err: any) {
      setError(err?.message || "Failed to load accounts.");
    } finally {
      setLoading(false);
    }
  }

  async function loadEntries(targetId: number | null, targetPeriod: string) {
    if (!targetId) return;
    setError("");
    try {
      const payload = await apiGet(`/reports/accounts/${targetId}/entries?period=${targetPeriod}`);
      setEntries(payload?.entries || []);
    } catch (err: any) {
      setError(err?.message || "Failed to load ledger entries.");
    }
  }

  useEffect(() => {
    loadAccounts();
  }, []);

  useEffect(() => {
    if (accountId) {
      loadEntries(accountId, period);
    }
  }, [accountId, period]);

  return (
    <div className="space-y-6">
      <div>
        <div className="h1">Ledger</div>
        <div className="subtle">Account-wise journal entries with period filter.</div>
      </div>

      {error ? <div className="danger">{error}</div> : null}

      <div className="card">
        <div className="toolbar">
          <label>
            Account:&nbsp;
            <select
              value={accountId ?? ""}
              onChange={(e) => setAccountId(Number(e.target.value))}
            >
              {accounts.map((acc) => (
                <option key={acc.id} value={acc.id}>
                  {acc.path || acc.name}
                </option>
              ))}
            </select>
          </label>
          <label>
            Period:&nbsp;
            <select value={period} onChange={(e) => setPeriod(e.target.value)}>
              {PERIODS.map((p) => (
                <option key={p.value} value={p.value}>
                  {p.label}
                </option>
              ))}
            </select>
          </label>
        </div>
      </div>

      {loading ? (
        <div className="meta">Loading accounts...</div>
      ) : (
        <div className="card">
          <table className="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Reference</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              {entries.length === 0 ? (
                <tr>
                  <td colSpan={4} className="meta">
                    No entries found for selected account.
                  </td>
                </tr>
              ) : null}
              {entries.map((entry) => (
                <tr key={entry.id}>
                  <td>{entry.entry_date}</td>
                  <td>{entry.description}</td>
                  <td>{entry.reference || "--"}</td>
                  <td>{entry.notes || "--"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// frontend/src/routes/ledger/+page.svelte
<script>
  import { onMount } from "svelte";
  import { apiGet } from "$lib/api";
  import { toPeriodParam } from "$lib/period";
  import { formatInr } from "$lib/format";
  import Table from "$lib/components/Table.svelte";

  let period = "current_month";
  let startDate = "";
  let endDate = "";
  let trial = null;
  let income = null;
  let error = "";
  let ready = false;

  const columns = [
    {
      header: "Account",
      render: (row) => `<a href="/journal-entries?account_id=${row.account.id}&period=${toPeriodParam(
        period,
        startDate,
        endDate
      )}">${row.account.path || row.account.name}</a>`
    },
    { header: "Type", render: (row) => row.account.account_type },
    { header: "Debit/Credit", render: (row) => row.type },
    { header: "Balance", render: (row) => formatInr(row.balance), align: "right" }
  ];

  async function load() {
    try {
      error = "";
      const [trialData, incomeData] = await Promise.all([
        apiGet(`/reports/trial-balance?period=${toPeriodParam(period, startDate, endDate)}`),
        apiGet(`/reports/income-statement?period=${toPeriodParam(period, startDate, endDate)}`)
      ]);
      trial = trialData;
      income = incomeData;
    } catch (err) {
      error = err.message || "Failed to load.";
    }
  }

  onMount(() => {
    ready = true;
  });
  $: if (ready) {
    period;
    startDate;
    endDate;
    load();
  }
</script>

<h1 class="page-title">Ledger</h1>
<p class="page-subtitle">Trial balance and income statement summary.</p>

{#if error}
  <p class="danger">{error}</p>
{/if}

<div class="toolbar">
  <label>
    Period:&nbsp;
    <select bind:value={period}>
      <option value="current_month">Current Month</option>
      <option value="ytd">Year to Date</option>
      <option value="all">All</option>
      <option value="custom">Custom Range</option>
    </select>
  </label>
  {#if period === "custom"}
    <label>
      Start:&nbsp;
      <input type="date" bind:value={startDate} />
    </label>
    <label>
      End:&nbsp;
      <input type="date" bind:value={endDate} />
    </label>
  {/if}
  <span class="meta">Net Income: {income ? formatInr(income.net_income) : "--"}</span>
</div>

<div class="panel">
  <div class="panel-row">
    <span class="panel-label">Trial Totals</span>
    <span class="panel-value">
      {trial ? formatInr(trial.total_debits) : "--"} / {trial ? formatInr(trial.total_credits) : "--"}
    </span>
  </div>
  <div class="panel-row">
    <span class="panel-label">Net Income</span>
    <span class="panel-value">{income ? formatInr(income.net_income) : "--"}</span>
  </div>
  <div class="panel-row">
    <span class="panel-label">Income vs Expense</span>
    <span class="panel-value">
      {income ? formatInr(income.total_income) : "--"} /{" "}
      {income ? formatInr(income.total_expenses) : "--"}
    </span>
  </div>
</div>

<Table {columns} rows={trial ? trial.account_balances : []} allowHtml={true} />
