// frontend/src/routes/income-statement/+page.svelte
<script>
  import { onMount } from "svelte";
  import { apiGet } from "$lib/api";
  import Table from "$lib/components/Table.svelte";
  import { toPeriodParam } from "$lib/period";
  import { formatInr } from "$lib/format";

  let period = "current_month";
  let startDate = "";
  let endDate = "";
  let showZero = false;
  let data = null;
  let error = "";
  let ready = false;

  function flatten(nodes) {
    const rows = [];
    nodes.forEach((node) => {
      rows.push({
        name: node.account.path || node.account.name,
        type: node.account.account_type,
        balance: node.balance,
        accountId: node.account.id
      });
      node.children?.forEach((child) => {
        rows.push({
          name: child.account.path || child.account.name,
          type: child.account.account_type,
          balance: child.balance,
          accountId: child.account.id
        });
        child.children?.forEach((gc) => {
          rows.push({
            name: gc.account.path || gc.account.name,
            type: gc.account.account_type,
            balance: gc.balance,
            accountId: gc.account.id
          });
        });
      });
    });
    return rows;
  }

  async function load() {
    try {
      error = "";
      const p = toPeriodParam(period, startDate, endDate);
      data = await apiGet(`/reports/income-statement?period=${p}&show_zero=${showZero ? "1" : "0"}`);
    } catch (err) {
      error = err.message || "Failed to load.";
    }
  }

  onMount(() => {
    ready = true;
  });

  $: if (ready) {
    period;
    startDate;
    endDate;
    showZero;
    load();
  }

  const columns = [
    {
      header: "Account",
      render: (row) => `<a href="/journal-entries?account_id=${row.accountId}&period=${toPeriodParam(
        period,
        startDate,
        endDate
      )}">${row.name}</a>`
    },
    { header: "Type", render: (row) => row.type },
    { header: "Balance", render: (row) => formatInr(row.balance), align: "right" }
  ];
</script>

<h1 class="page-title">Income Statement</h1>
<p class="page-subtitle">Income and expense performance for the selected period.</p>

{#if error}
  <p class="danger">{error}</p>
{/if}

<div class="toolbar">
  <label>
    Period:&nbsp;
    <select bind:value={period}>
      <option value="current_month">Current Month</option>
      <option value="ytd">Year to Date</option>
      <option value="all">All</option>
      <option value="custom">Custom Range</option>
    </select>
  </label>
  {#if period === "custom"}
    <label>
      Start:&nbsp;
      <input type="date" bind:value={startDate} />
    </label>
    <label>
      End:&nbsp;
      <input type="date" bind:value={endDate} />
    </label>
  {/if}
  <label>
    <input type="checkbox" bind:checked={showZero} />
    &nbsp;Show Zero Balances
  </label>
  <span class="meta">Net Income: {data ? formatInr(data.net_income) : "--"}</span>
</div>

<div class="panel">
  <div class="panel-row">
    <span class="panel-label">Net Income</span>
    <span class="panel-value">{data ? formatInr(data.net_income) : "--"}</span>
  </div>
  <div class="panel-row">
    <span class="panel-label">Income</span>
    <span class="panel-value">{data ? formatInr(data.total_income) : "--"}</span>
  </div>
  <div class="panel-row">
    <span class="panel-label">Expenses</span>
    <span class="panel-value">{data ? formatInr(data.total_expenses) : "--"}</span>
  </div>
</div>

<Table
  {columns}
  rows={data ? [
    ...flatten(data.income_accounts),
    ...flatten(data.expense_accounts)
  ] : []}
  allowHtml={true}
/>

// nodeapp/web/src/app/income-statement/page.tsx
"use client";

import { useEffect, useState } from "react";
import { apiGet } from "@/lib/api";

type AccountNode = {
  account: { id: number; name: string; path?: string };
  balance: number;
  children?: AccountNode[];
};

type ReportPayload = {
  income_accounts: AccountNode[];
  expense_accounts: AccountNode[];
  total_income: number;
  total_expenses: number;
  net_income: number;
  period: string;
  start_date: string | null;
  end_date: string | null;
};

const PERIODS = [
  { value: "current_month", label: "Current Month" },
  { value: "ytd", label: "Year to Date" },
  { value: "all", label: "All Time" }
];

function formatMoney(value: number) {
  const num = Number(value || 0);
  const prefix = num < 0 ? "-Rs " : "Rs ";
  return `${prefix}${Math.abs(num).toLocaleString("en-IN")}`;
}

function renderRows(nodes: AccountNode[], depth = 0): JSX.Element[] {
  return nodes.flatMap((node) => {
    const rows = [
      <tr key={`${node.account.id}-${depth}`}>
        <td style={{ paddingLeft: depth * 16 }}>{node.account.name}</td>
        <td className="num">{formatMoney(node.balance)}</td>
      </tr>
    ];
    if (node.children && node.children.length) {
      rows.push(...renderRows(node.children, depth + 1));
    }
    return rows;
  });
}

export default function Page() {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [period, setPeriod] = useState("current_month");
  const [report, setReport] = useState<ReportPayload | null>(null);

  async function load(targetPeriod: string) {
    setLoading(true);
    setError("");
    try {
      const payload = await apiGet(`/reports/income-statement?period=${targetPeriod}`);
      setReport(payload);
    } catch (err: any) {
      setError(err?.message || "Failed to load income statement.");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load(period);
  }, [period]);

  return (
    <div className="space-y-6">
      <div>
        <div className="h1">Income Statement</div>
        <div className="subtle">Income vs expense for the selected period.</div>
      </div>

      {error ? <div className="danger">{error}</div> : null}

      <div className="card">
        <div className="toolbar">
          <label>
            Period:&nbsp;
            <select value={period} onChange={(e) => setPeriod(e.target.value)}>
              {PERIODS.map((p) => (
                <option key={p.value} value={p.value}>
                  {p.label}
                </option>
              ))}
            </select>
          </label>
          {report?.start_date || report?.end_date ? (
            <span className="meta">
              {report?.start_date || "--"} to {report?.end_date || "--"}
            </span>
          ) : null}
        </div>
      </div>

      {loading ? (
        <div className="meta">Loading...</div>
      ) : (
        <>
          <div className="card">
            <div className="panel-row">
              <span className="panel-label">Total Income</span>
              <span className="panel-value">{formatMoney(report?.total_income || 0)}</span>
            </div>
            <div className="panel-row">
              <span className="panel-label">Total Expenses</span>
              <span className="panel-value">{formatMoney(report?.total_expenses || 0)}</span>
            </div>
            <div className="panel-row">
              <span className="panel-label">Net Income</span>
              <span className="panel-value">{formatMoney(report?.net_income || 0)}</span>
            </div>
          </div>

          <div className="card">
            <div className="h1" style={{ fontSize: 16, marginBottom: 8 }}>
              Income
            </div>
            <table className="table">
              <thead>
                <tr>
                  <th>Account</th>
                  <th className="num">Amount</th>
                </tr>
              </thead>
              <tbody>
                {report?.income_accounts?.length ? (
                  renderRows(report.income_accounts)
                ) : (
                  <tr>
                    <td colSpan={2} className="meta">
                      No income accounts for this period.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          <div className="card">
            <div className="h1" style={{ fontSize: 16, marginBottom: 8 }}>
              Expenses
            </div>
            <table className="table">
              <thead>
                <tr>
                  <th>Account</th>
                  <th className="num">Amount</th>
                </tr>
              </thead>
              <tbody>
                {report?.expense_accounts?.length ? (
                  renderRows(report.expense_accounts)
                ) : (
                  <tr>
                    <td colSpan={2} className="meta">
                      No expense accounts for this period.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </>
      )}
    </div>
  );
}
